# Generated by Django 3.2 on 2022-04-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patronym',
            field=models.CharField(default='', max_length=100, verbose_name='А ты кто?'),
        ),
    ]
