# Generated by Django 3.2 on 2022-04-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220427_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_student',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
    ]
