# Generated by Django 3.2 on 2022-05-19 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_russian', models.CharField(max_length=300, verbose_name='Название на русском')),
                ('name_english', models.CharField(max_length=300, verbose_name='Название на английском')),
                ('description', models.TextField(verbose_name='Краткое описание темы')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRequestForTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Опишите свои интересы')),
                ('responded', models.BooleanField(default=False)),
                ('lecturer_answer', models.TextField(default='', max_length=2000)),
                ('declined', models.BooleanField(default=False)),
                ('no_topic', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('associatedTopic', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='test_app.topic')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=2000, verbose_name='Введите ваш ответ (до 2000 символов)')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('associatedRequest', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='test_app.studentrequestfortopic')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
