# Generated by Django 3.2 on 2022-04-30 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_app', '0019_auto_20210510_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_russian', models.CharField(max_length=300, verbose_name='Название на русском')),
                ('name_english', models.CharField(max_length=300, verbose_name='Название на английском')),
                ('description', models.TextField(verbose_name='Краткое описание темы')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
