# Generated by Django 3.2 on 2022-04-30 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_app', '0020_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequestForTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Опишите свои интересы')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('associatedTopic', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='test_app.topic')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
