# Generated by Django 3.2 on 2022-04-30 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_app', '0021_studentrequestfortopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequestfortopic',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentrequestfortopic',
            name='responded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('associatedRequest', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='test_app.studentrequestfortopic')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
