# Generated by Django 3.2 on 2022-04-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0022_auto_20220430_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='content',
            field=models.TextField(verbose_name='Впишите ответ сюда'),
        ),
    ]
