# Generated by Django 3.2 on 2022-04-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0023_alter_response_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequestfortopic',
            name='no_topic',
            field=models.BooleanField(default=False),
        ),
    ]
