# Generated by Django 3.2 on 2022-05-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0024_studentrequestfortopic_no_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequestfortopic',
            name='answer',
            field=models.TextField(default='', verbose_name='Введите ваш ответ'),
        ),
    ]
