# Generated by Django 3.2 on 2022-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0025_studentrequestfortopic_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrequestfortopic',
            name='answer',
        ),
        migrations.AlterField(
            model_name='requestresponse',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='Введите ваш ответ (до 2000 символов)'),
        ),
    ]
