# Generated by Django 3.2 on 2022-05-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0026_auto_20220511_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequestfortopic',
            name='lecturer_answer',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
