# Generated by Django 3.2 on 2022-05-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0027_studentrequestfortopic_lecturer_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='associated_vacancy',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='author',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='author',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
